---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: lootchat-backend
  namespace: flux-system
spec:
  image: babou212/lootchat-backend
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: lootchat-frontend
  namespace: flux-system
spec:
  image: babou212/lootchat-frontend
  interval: 5m
